### ISSUE TITLE
Remove the need to explicitly define which files to compile using FSharp

### ISSUE THREAD

**Issue by wmeints** [fsprojects/fsharp-dnx#31]
Hi, I just tried to integrate the F# compiler into my DNX project and I am surprised how well it works!
The only problem I ran into immediately is the fact that I need to explicitly define the input files for the F# compiler. 

Is it at all possible to remove this requirement? It would make my life a lot easier.
I don't need to specify inputs for the C# compiler, so I'd expect that I don't need to specify them for F# either.

**Comment by Alxandr** [comment]
It's not possible, because as opposed to the C# compiler, the F# compiler needs the files to be in correct order. If you don't specify the files manually, how will we know how to order them? Alphabetically? By last save date?

With tooling, these problems will be alleviated/go away, but for now you're stuck with manually specifying them unfortunately.

Oh, and just as a hint, DNX is "going away" in RC2, and dotnet CLI is the new, so this project will soon be rendered useless. F# support for dotnet cli has been completed already as far as I know, but not by me.

**Comment by wmeints** [comment]
Noted, I just discovered the new dotnet functionality to build F# projects.
Thanks for clarifying :-)
