### ISSUE TITLE
startup time is real slow

### ISSUE THREAD

**Issue by s-trooper** [fsprojects/fsharp-dnx#4]
Hi, i am aware it is beta time but for info. Startup time of sample\HelloFSharp is 4.5 sec vs 0.5 sec of C# "hello world" with same dnx runtime. Windows 7 64-Bit.

**Comment by Alxandr** [comment]
This is due to several reasons. First of, when you're running the sample, your first compiling the F# compiler (not the actual compiler, but the YoloDev.Dnx.FSharp bridge), then you're loading the actual F# compiler, then your compiling your application to disk (which does a large amount of IO because the F# compiler was never made to support this kind of thing), then the compiled assembly is loaded into memory (so the on-disk ones can be cleaned up), and **then** your application can load and run. Most of these I can't do anything about, thus closing the issue. 

Btw, try running a project with the compiled F# compiler instead. Should help a bit.
